repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md,markdown
    -   id: end-of-file-fixer
    -   id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args:
          - --ignore-missing-imports
          - --scripts-are-modules
          - --allow-untyped-decorators
        require_serial: true
        exclude: tests/
        additional_dependencies:
          - 'pydantic'

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
        - id: pylint
          types: [ python ]
          args:
            - --errors-only
            - --disable=import-error
